"""updated feedback table

Revision ID: 469de81d333a
Revises: b8d6534dc23f
Create Date: 2026-02-02 14:12:26.232016

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469de81d333a'
down_revision: Union[str, Sequence[str], None] = 'b8d6534dc23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('feedback', sa.Column('user_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('feedback', sa.Column('ai_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('feedback', sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('feedback', 'thread_id')
    op.drop_column('feedback', 'message_index')
    op.drop_column('feedback', 'feedback_type')
    op.drop_column('feedback', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('feedback_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('message_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('thread_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('feedback', 'sentiment')
    op.drop_column('feedback', 'ai_response')
    op.drop_column('feedback', 'user_query')
    op.drop_column('feedback', 'rating')
    # ### end Alembic commands ###
