"""add chat_message

Revision ID: 858162790073
Revises: 252a3b4fe17c
Create Date: 2026-01-04 21:41:44.547635

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '858162790073'
down_revision: Union[str, Sequence[str], None] = '252a3b4fe17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ticket_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_thread_id'), 'chatmessage', ['thread_id'], unique=False)
    op.create_index(op.f('ix_chatmessage_ticket_id'), 'chatmessage', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessage_ticket_id'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_thread_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    # ### end Alembic commands ###
